name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Upload Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release APK
        run: gradle assembleRelease --no-daemon

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: TUNZY-release-apk
          path: "**/build/outputs/apk/release/*.apk"
          retention-days: 30